### ISSUE TITLE
Error in nhc/helpers/node-mark-offline

### ISSUE THREAD

**Issue by quasigeek** [mej/nhc#108] opened 2021-10-19 23:33 UTC
Hi,

There seems to be an error in the script nhc/helpers/node-mark-offline.
there is a missing ";;" between line 69 and 70 to properly pass from one "case" statement to the other.

```
    case "$STATUS" in
        *'@'*|*'#'*|boot*)
            # These states aren't handled yet.
            echo "$0:  State \"$STATUS\" not yet handled; ignoring."
            exit 0
        alloc*|comp*|drain*|drng*|fail*|idle*|maint*|mix*|resume*|resv*|undrain*)
            case "$STATUS" in
                drain*|drng*|fail*|maint*)
                    # If the node is already offline, and there is no old note, and
                    # we've not been told to ignore that, do not touch the node.
...
```

should be:
```
    case "$STATUS" in
        *'@'*|*'#'*|boot*)
            # These states aren't handled yet.
            echo "$0:  State \"$STATUS\" not yet handled; ignoring."
            exit 0
            ;;
        alloc*|comp*|drain*|drng*|fail*|idle*|maint*|mix*|resume*|resv*|undrain*)
            case "$STATUS" in
                drain*|drng*|fail*|maint*)
                    # If the node is already offline, and there is no old note, and
                    # we've not been told to ignore that, do not touch the node.
...
```

**Comment by mej** [comment] 2023-03-04 07:46
This was fixed in PR #107 with commit [2ecacfe8](https://github.com/mej/nhc/commit/2ecacfe82928a9a6e41283e78617c28a795db2af); duplicate of #103.  Closing.

**Closed by mej** 2023-03-04 07:46 UTC
Labels: duplicate, invalid
