### ISSUE TITLE
NHC on Centos/7.4 - problem generating rpm - fail test lbnl_file.nhc

### ISSUE THREAD

**Issue by maoliveirahpc** [mej/nhc#55] opened 2018-02-27 17:02 UTC
Hi all,

I am trying to generate the rpm to deploy on our cluster here but the usual procedure I follow is giving me errors on Centos 7.4.
For a straight rpm build I get:

[root@nslurmdb1 nhc]# rpmbuild --rebuild lbnl-nhc-1.4.2-1.el7.src.rpm 
Installing lbnl-nhc-1.4.2-1.el7.src.rpm
warning: user mej does not exist - using root
warning: group mej does not exist - using root
warning: user mej does not exist - using root
warning: group mej does not exist - using root
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.iZv7yu
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd /root/rpmbuild/BUILD
+ rm -rf lbnl-nhc-1.4.2
+ /usr/bin/gzip -dc /root/rpmbuild/SOURCES/lbnl-nhc-1.4.2.tar.gz
+ /usr/bin/tar -xvvf -
drwxr-xr-x 1000/1000         0 2015-11-11 21:11 lbnl-nhc-1.4.2/
-rw-r--r-- 1000/1000     25217 2015-11-11 21:11 lbnl-nhc-1.4.2/aclocal.m4
-rw-r--r-- 1000/1000      2508 2015-10-14 02:13 lbnl-nhc-1.4.2/LICENSE
-rw-r--r-- 1000/1000      6340 2015-10-14 02:13 lbnl-nhc-1.4.2/nhc.conf
drwxr-xr-x 1000/1000         0 2015-11-11 21:11 lbnl-nhc-1.4.2/test/
-rw-r--r-- 1000/1000      4314 2015-10-14 02:13 lbnl-nhc-1.4.2/test/test_lbnl_nv.nhc
-rw-r--r-- 1000/1000     11140 2015-10-14 02:13 lbnl-nhc-1.4.2/test/test_lbnl_hw.nhc
-rw-r--r-- 1000/1000     11131 2015-11-11 21:11 lbnl-nhc-1.4.2/test/Makefile.in
-rw-r--r-- 1000/1000      2243 2015-10-14 02:13 lbnl-nhc-1.4.2/test/test_lbnl_cmd.nhc
-rw-r--r-- 1000/1000     14050 2015-10-14 02:13 lbnl-nhc-1.4.2/test/test_common.nhc
-rw-r--r-- 1000/1000       343 2015-10-14 02:13 lbnl-nhc-1.4.2/test/test_lbnl_moab.nhc
-rw-r--r-- 1000/1000     20813 2015-11-11 20:56 lbnl-nhc-1.4.2/test/test_lbnl_ps.nhc
-rw-r--r-- 1000/1000     12770 2015-10-14 02:13 lbnl-nhc-1.4.2/test/test_lbnl_dmi.nhc
-rw-r--r-- 1000/1000       475 2015-10-14 02:13 lbnl-nhc-1.4.2/test/Makefile.am
-rw-r--r-- 1000/1000     12745 2015-10-14 02:13 lbnl-nhc-1.4.2/test/test_lbnl_fs.nhc
-rw-r--r-- 1000/1000      8514 2015-10-14 02:13 lbnl-nhc-1.4.2/test/test_lbnl_net.nhc
-rw-r--r-- 1000/1000       322 2015-10-14 02:13 lbnl-nhc-1.4.2/test/test_lbnl_job.nhc
-rw-r--r-- 1000/1000      5148 2015-10-14 02:13 lbnl-nhc-1.4.2/test/shut.inc.sh
-rw-r--r-- 1000/1000     12362 2015-10-14 02:13 lbnl-nhc-1.4.2/test/test_lbnl_file.nhc
-rwxr-xr-x 1000/1000      7541 2015-10-14 02:13 lbnl-nhc-1.4.2/test/nhc-test
drwxr-xr-x 1000/1000         0 2015-11-11 21:11 lbnl-nhc-1.4.2/bench/
-rw-r--r-- 1000/1000     10768 2015-11-11 21:11 lbnl-nhc-1.4.2/bench/Makefile.in
-rw-r--r-- 1000/1000       109 2015-10-14 02:13 lbnl-nhc-1.4.2/bench/Makefile.am
drwxr-xr-x 1000/1000         0 2015-11-11 21:11 lbnl-nhc-1.4.2/contrib/
-rw-r--r-- 1000/1000       756 2015-10-14 02:10 lbnl-nhc-1.4.2/contrib/nhc.cron
-rwxr-xr-x 1000/1000     16160 2015-10-14 02:13 lbnl-nhc-1.4.2/nhc-genconf
-rw-r--r-- 1000/1000     31533 2015-11-11 21:11 lbnl-nhc-1.4.2/Makefile.in
drwxr-xr-x 1000/1000         0 2015-11-11 21:11 lbnl-nhc-1.4.2/scripts/
-rw-r--r-- 1000/1000     13215 2015-10-14 02:13 lbnl-nhc-1.4.2/scripts/lbnl_net.nhc
-rw-r--r-- 1000/1000     20358 2015-10-14 02:13 lbnl-nhc-1.4.2/scripts/common.nhc
-rw-r--r-- 1000/1000      4819 2015-10-14 02:13 lbnl-nhc-1.4.2/scripts/lbnl_moab.nhc
-rw-r--r-- 1000/1000      1250 2015-10-14 02:13 lbnl-nhc-1.4.2/scripts/lbnl_nv.nhc
-rw-r--r-- 1000/1000     19698 2015-10-14 02:13 lbnl-nhc-1.4.2/scripts/lbnl_fs.nhc
-rw-r--r-- 1000/1000      8272 2015-11-11 20:56 lbnl-nhc-1.4.2/scripts/lbnl_cmd.nhc
-rw-r--r-- 1000/1000     14024 2015-10-14 02:13 lbnl-nhc-1.4.2/scripts/lbnl_file.nhc
-rw-r--r-- 1000/1000      3808 2015-10-14 02:13 lbnl-nhc-1.4.2/scripts/lbnl_job.nhc
-rw-r--r-- 1000/1000      7886 2015-10-14 02:13 lbnl-nhc-1.4.2/scripts/lbnl_dmi.nhc
-rw-r--r-- 1000/1000     31697 2015-11-11 20:56 lbnl-nhc-1.4.2/scripts/lbnl_ps.nhc
-rw-r--r-- 1000/1000     14980 2015-10-14 02:13 lbnl-nhc-1.4.2/scripts/lbnl_hw.nhc
-rwxr-xr-x 1000/1000       216 2015-10-14 02:10 lbnl-nhc-1.4.2/autogen.sh
-rwxr-xr-x 1000/1000     23116 2015-11-11 20:56 lbnl-nhc-1.4.2/nhc
-rwxr-xr-x 1000/1000      6873 2015-11-11 21:11 lbnl-nhc-1.4.2/missing
-rw-r--r-- 1000/1000       952 2015-10-14 02:13 lbnl-nhc-1.4.2/configure.ac
-rw-r--r-- 1000/1000      2536 2015-11-11 21:11 lbnl-nhc-1.4.2/lbnl-nhc.spec
-rw-r--r-- 1000/1000        30 2015-10-14 02:13 lbnl-nhc-1.4.2/nhc-test.conf
-rwxr-xr-x 1000/1000     13997 2015-11-11 21:11 lbnl-nhc-1.4.2/install-sh
-rw-r--r-- 1000/1000      1394 2015-10-14 02:13 lbnl-nhc-1.4.2/Makefile.am
-rwxr-xr-x 1000/1000     12669 2015-10-14 02:13 lbnl-nhc-1.4.2/nhc-wrapper
-rwxr-xr-x 1000/1000    103144 2015-11-11 21:11 lbnl-nhc-1.4.2/configure
-rw-r--r-- 1000/1000     50966 2015-10-14 02:10 lbnl-nhc-1.4.2/ChangeLog
drwxr-xr-x 1000/1000         0 2015-11-11 21:11 lbnl-nhc-1.4.2/helpers/
-rw-r--r-- 1000/1000      5383 2015-10-14 02:13 lbnl-nhc-1.4.2/helpers/node-mark-offline
-rw-r--r-- 1000/1000      5402 2015-10-14 02:13 lbnl-nhc-1.4.2/helpers/node-mark-online
-rw-r--r-- 1000/1000        31 2015-10-14 02:10 lbnl-nhc-1.4.2/COPYING
-rw-r--r-- 1000/1000      2548 2015-11-11 21:07 lbnl-nhc-1.4.2/lbnl-nhc.spec.in
-rw-r--r-- 1000/1000        95 2015-10-14 02:13 lbnl-nhc-1.4.2/nhc.logrotate
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd lbnl-nhc-1.4.2
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.TIVW18
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd lbnl-nhc-1.4.2
+ CFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic'
+ export CFLAGS
+ CXXFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic'
+ export CXXFLAGS
+ FFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro '
+ export LDFLAGS
+ '[' 1 == 1 ']'
+ '[' x86_64 == ppc64le ']'
++ find . -name config.guess -o -name config.sub
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info
configure: WARNING: unrecognized options: --disable-dependency-tracking
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for Git version description... 1.4.2
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating bench/Makefile
config.status: creating test/Makefile
config.status: creating lbnl-nhc.spec
configure: WARNING: unrecognized options: --disable-dependency-tracking
+ /usr/bin/make
Making all in bench
make[1]: Entering directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/bench'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/bench'
Making all in test
make[1]: Entering directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/test'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/test'
make[1]: Entering directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2'
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.YjEJzR
+ umask 022
+ cd /root/rpmbuild/BUILD
+ '[' /root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64 '!=' / ']'
+ rm -rf /root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64
++ dirname /root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64
+ mkdir -p /root/rpmbuild/BUILDROOT
+ mkdir /root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64
+ cd lbnl-nhc-1.4.2
+ umask 0077
+ /usr/bin/make install DESTDIR=/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64
Making install in bench
make[1]: Entering directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/bench'
make[2]: Entering directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/bench'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/bench'
make[1]: Leaving directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/bench'
Making install in test
make[1]: Entering directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/test'
make[2]: Entering directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/test'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/test'
make[1]: Leaving directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/test'
make[1]: Entering directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2'
make[2]: Entering directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2'
 /usr/bin/mkdir -p '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/usr/sbin'
 /usr/bin/install -c nhc nhc-genconf nhc-wrapper '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/usr/sbin'
/usr/bin/mkdir -p '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/etc/logrotate.d' '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/var/lib/nhc' '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/var/run/nhc'
/usr/bin/install -c -m 644 ./nhc.logrotate '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/etc/logrotate.d/nhc'
 /usr/bin/mkdir -p '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/etc/nhc'
 /usr/bin/install -c -m 644 nhc.conf '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/etc/nhc'
 /usr/bin/mkdir -p '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/usr/libexec/nhc'
 /usr/bin/install -c helpers/node-mark-online helpers/node-mark-offline '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/usr/libexec/nhc'
 /usr/bin/mkdir -p '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/etc/nhc'
 /usr/bin/mkdir -p '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/etc/nhc/scripts'
 /usr/bin/install -c -m 644  scripts/lbnl_cmd.nhc scripts/common.nhc scripts/lbnl_dmi.nhc scripts/lbnl_file.nhc scripts/lbnl_fs.nhc scripts/lbnl_hw.nhc scripts/lbnl_job.nhc scripts/lbnl_moab.nhc scripts/lbnl_net.nhc scripts/lbnl_nv.nhc scripts/lbnl_ps.nhc '/root/rpmbuild/BUILDROOT/lbnl-nhc-1.4.2-1.el7.centos.x86_64/etc/nhc/scripts'
make[2]: Leaving directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2'
make[1]: Leaving directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2'
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /root/rpmbuild/BUILD/lbnl-nhc-1.4.2
/usr/lib/rpm/sepdebugcrcfix: Updated 0 CRC32s, 0 CRC32s did match.
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.Z6sEMA
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd lbnl-nhc-1.4.2
+ /usr/bin/make test
/usr/bin/make -C test test
make[1]: Entering directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/test'
Running unit tests for NHC:
nhcmain_init_env...ok 6/6
nhcmain_help...ok 8/8
nhcmain_parse_cmdline...ok 16/16
nhcmain_finalize_env...ok 14/14
nhcmain_check_conffile...ok 1/1
nhcmain_load_scripts...ok 6/6
nhcmain_set_watchdog...ok 1/1
nhcmain_watchdog_timer...ok 3/3
nhcmain_run_checks...ok 2/2
common.nhc...ok 108/108
lbnl_cmd.nhc...ok 13/13
lbnl_dmi.nhc...ok 45/45
lbnl_file.nhc...../scripts/lbnl_file.nhc: line 83: /dev/fd/63: No such file or directory
failed 4/71
TEST FAILED:  Single regexp match success:  Got "1" but expected "0"
make[1]: *** [test] Error 255
make[1]: Leaving directory `/root/rpmbuild/BUILD/lbnl-nhc-1.4.2/test'
make: *** [test] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.Z6sEMA (%check)

RPM build errors:
    user mej does not exist - using root
    group mej does not exist - using root
    user mej does not exist - using root
    group mej does not exist - using root
    Bad exit status from /var/tmp/rpm-tmp.Z6sEMA (%check)

Doing an autogen, configure, make test does not give this error from a git clone.

I did not have this problem on Centos 7.3.

Any idea on what is going on?

Best Regards,

Miguel Afonso Oliveira

**Comment by mej** [comment] 2018-02-27 21:42
This is a duplicate of #31 and is fixed by 212f4f0.

**Closed by mej** 2018-02-27 21:42 UTC
Labels: duplicate
